[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "petcosttracker"
version = "1.0.0"
dependencies = []
[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.2"